# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from

minimal_mistakes_skin: "dark" 
# Site Settings
locale: "en-US"
title: "MSFTPlayground"
title_separator: "-"
subtitle: "Debug.Write('Architecture, Azure, Azure DevOps, Git, GitHub, DevOps')"
name: "Maik van der Gaag"
description: ""
url: # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: "/"
repository: "maikvandergaag/maikvandergaag.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
future: true
words_per_minute: 200
# Social Sharing
twitter:
  username: "maikvandergaag"
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type: Person
  name: Maik van der Gaag
  links: # An array of links to social media profiles
    - https://twitter.com/maikvandergaag
    - https://github.com/maikvandergaag
    - https://www.linkedin.com/in/maikvandergaag/
 # Site Author
author:
  name: "Maik van der Gaag"
  avatar: ""
  bio: "I am a **father**, **CTO**, **MVP**, and **speaker**."
  location: "Schiedam, Netherlands"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/maikvandergaag"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/maikvandergaag"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/maikvandergaag"
# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/maikvandergaag"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/maikvandergaag"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/maikvandergaag"
