name: Rebuild

on:
  schedule:
    - cron:  '0 5 * * *' # Runs every day at 6am
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Call GitHub pages build endpoint
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/maikvandergaag/maikvandergaag.github.io/pages/builds \
            --header "Authorization: Bearer $GH_TOKEN"          
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
